### PR TITLE
Use decorators

### PR DESCRIPTION
**Pull request by martndemus**

### CODE REVIEW

**Comment by rwjblue** [comment]
Hmm.  We need to test what this looks like for apps that include this addon.  The changes in ember-cli-build.js are only for developing this addon itself, but we need to enable the decorator plugin either way.

I would suggest not changing `ember-cli-build.js` and making this work via changes in `index.js` only.  I think that is a better simulation of "real" world app inclusion.

**Comment by martndemus** [comment]
I am not sure what strategy I am heading towards, these are some of my thoughts:

- asking users of the addon to do something is a no no.
- gnerating a .babelrc might be a temporary solution
- maybe there is a programmatic way to manip babel.
- I think there might be another hook (pre-configure?) needed on ember-cli.

**Comment by rwjblue** [comment]
You should be able to set `options` in `init` to provide your own `babel` instance with its config.

Something like (pseudo code):

```js
init: function() {
  this.options = {
    babel: {
      optional: ['es7.decorators']
    }
  }
}
```

**Comment by martndemus** [comment]
@rwjblue: thanks!

**Comment by rwjblue** [comment]
HA!  Apparently that works ;P

**Comment by martndemus** [comment]
I must admit that it took me a little while to notice you had written `init` and not `included`.

**Comment by rwjblue** [comment]
@martndemus - Would you mind adding a small blurb in the `ember-computed-decorators` README with your `init` snippet?

**Comment by martndemus** [comment]
@rwjblue Not at all!

**Pull request merged**
